#!/usr/bin/env bash
# Script to run pipeline 10 times on medium CSV and 10 times on production CSV.
# Saves state dicts and execution logs uniquely for each run, categorized by model.
# Prints outputs, ensures only the latest generated script is executed, and resets the repository state.

set -euo pipefail

# Get project root directory
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Prepend project root to PYTHONPATH so imports resolve correctly
export PYTHONPATH="$ROOT${PYTHONPATH:+:$PYTHONPATH}"

echo "Tip: Make sure you have activated your environment (e.g., conda activate texprompting)" >&2

# Cleanup function to reset TestOutputs/ only
cleanup() {
    echo ""
    echo "=== Resetting changes (cleanup) ==="
    git restore TestOutputs/ 2>/dev/null || git checkout -- TestOutputs/
    git clean -fd TestOutputs/
}

# Register the cleanup function to always run on script exit
trap cleanup EXIT

# Define files to run
MEDIUM_CSV="optimization_pipeline_test_medium.csv"
PRODUCTION_CSV="versatile_producion_system/Production.csv"

# ----------------- RUN MEDIUM: 10 TIMES -----------------
echo ""
echo "========================================================================="
echo "Running MEDIUM dataset ($MEDIUM_CSV) 10 times"
echo "========================================================================="

for i in {1..10}; do
    echo ""
    echo "----------------------------------------"
    echo "Starting MEDIUM Run ${i}/10"
    echo "----------------------------------------"

    # Execute the pipeline with mocked mlflow, ensure only latest generated script is run
    python -c "
import sys
from types import ModuleType

# Mock MLflow to disable and ignore tracking/autologging completely
class MockMLflow(ModuleType):
    def __getattr__(self, name):
        if name == 'langchain':
            return self
        return lambda *args, **kwargs: None
sys.modules['mlflow'] = MockMLflow('mlflow')

import json
import os
import re
from pathlib import Path
from orchestrator.pipeline import run_pipeline
from agents.shared import execute_generated_pulp_model, get_test_outputs_dir

# 1. Prep: delete existing generated_pulp_model.py to ensure we only run a newly generated one
pulp_script_path = get_test_outputs_dir() / 'generated_pulp_model.py'
if pulp_script_path.exists():
    pulp_script_path.unlink()

# 2. Run pipeline (uses default preview_rows)
print('[run_experiments] Launching pipeline for medium CSV...')
state = run_pipeline('$MEDIUM_CSV')

# 3. Print output of run_pipeline to stdout
print('\n[run_experiments] Output of run_pipeline (Final State Dict):')
print(state.model_dump_json(indent=2))

# 4. Get sanitized model name from environment
model_name = os.getenv('OLLAMA_MODEL', 'qwen3.6:latest')
model_clean = re.sub(r'[^a-zA-Z0-9_\\-]', '_', model_name)

# 5. Save state dict
state_dict_file = f'result_{model_clean}_medium_run_${i}_state_dict.json'
with open(state_dict_file, 'w', encoding='utf-8') as f:
    f.write(state.model_dump_json(indent=2))
print(f'\n[run_experiments] Saved state dict to {state_dict_file}')

# 6. Check and execute ONLY if a new script was successfully generated in this run
exec_output_file = f'result_{model_clean}_medium_run_${i}_execution_output.log'
if pulp_script_path.exists():
    try:
        print('[run_experiments] Testing execution of generated PuLP script...')
        exec_output = execute_generated_pulp_model()
        print('[run_experiments] SUCCESS: Generated script executed cleanly!')
    except Exception as e:
        exec_output = str(e)
        print(f'[run_experiments] FAILURE: Generated script execution failed: {e}')
else:
    exec_output = 'Error: No pulp script was generated in this run.'
    print('[run_experiments] FAILURE: No script was generated by the scripting agent.')

# 7. Save execution output
with open(exec_output_file, 'w', encoding='utf-8') as f:
    f.write(exec_output)
print(f'[run_experiments] Saved execution output to {exec_output_file}')
"

    # Revert and clean up after this run
    cleanup
    echo "--- Finished MEDIUM Run ${i}/10 ---"
done


# ----------------- RUN PRODUCTION: 10 TIMES -----------------
echo ""
echo "========================================================================="
echo "Running PRODUCTION dataset ($PRODUCTION_CSV) 10 times"
echo "========================================================================="

for i in {1..10}; do
    echo ""
    echo "----------------------------------------"
    echo "Starting PRODUCTION Run ${i}/10"
    echo "----------------------------------------"

    # Execute the pipeline with mocked mlflow, ensure only latest generated script is run
    python -c "
import sys
from types import ModuleType

# Mock MLflow to disable and ignore tracking/autologging completely
class MockMLflow(ModuleType):
    def __getattr__(self, name):
        if name == 'langchain':
            return self
        return lambda *args, **kwargs: None
sys.modules['mlflow'] = MockMLflow('mlflow')

import json
import os
import re
from pathlib import Path
from orchestrator.pipeline import run_pipeline
from agents.shared import execute_generated_pulp_model, get_test_outputs_dir

# 1. Prep: delete existing generated_pulp_model.py to ensure we only run a newly generated one
pulp_script_path = get_test_outputs_dir() / 'generated_pulp_model.py'
if pulp_script_path.exists():
    pulp_script_path.unlink()

# 2. Run pipeline (uses default preview_rows)
print('[run_experiments] Launching pipeline for production CSV...')
state = run_pipeline('$PRODUCTION_CSV')

# 3. Print output of run_pipeline to stdout
print('\n[run_experiments] Output of run_pipeline (Final State Dict):')
print(state.model_dump_json(indent=2))

# 4. Get sanitized model name from environment
model_name = os.getenv('OLLAMA_MODEL', 'qwen3.6:latest')
model_clean = re.sub(r'[^a-zA-Z0-9_\\-]', '_', model_name)

# 5. Save state dict
state_dict_file = f'result_{model_clean}_production_run_${i}_state_dict.json'
with open(state_dict_file, 'w', encoding='utf-8') as f:
    f.write(state.model_dump_json(indent=2))
print(f'\n[run_experiments] Saved state dict to {state_dict_file}')

# 6. Check and execute ONLY if a new script was successfully generated in this run
exec_output_file = f'result_{model_clean}_production_run_${i}_execution_output.log'
if pulp_script_path.exists():
    try:
        print('[run_experiments] Testing execution of generated PuLP script...')
        exec_output = execute_generated_pulp_model()
        print('[run_experiments] SUCCESS: Generated script executed cleanly!')
    except Exception as e:
        exec_output = str(e)
        print(f'[run_experiments] FAILURE: Generated script execution failed: {e}')
else:
    exec_output = 'Error: No pulp script was generated in this run.'
    print('[run_experiments] FAILURE: No script was generated by the scripting agent.')

# 7. Save execution output
with open(exec_output_file, 'w', encoding='utf-8') as f:
    f.write(exec_output)
print(f'[run_experiments] Saved execution output to {exec_output_file}')
"

    # Revert and clean up after this run
    cleanup
    echo "--- Finished PRODUCTION Run ${i}/10 ---"
done

echo ""
echo "========================================================================="
echo "All 20 runs completed successfully!"
echo "Saved files:"
echo "  - result_*_run_*_state_dict.json"
echo "  - result_*_run_*_execution_output.log"
echo "========================================================================="
