# This Agent is designed to generate pulp code for a given optimization problem. It takes in the mathematical formulation (input scheme, output scheme and Model)
# of the optimization problem generated by the Mathematical_Reasoning_Agent and the csv to input schema code generated by the Input_Schema_to_Code_Agent
# and then generates the full pulp code to solve the optimization problem. 
# The agent is designed to be used in a pipeline after the Mathematical_Reasoning_Agent and the Input_Schema_to_Code_Agent, and it uses the outputs of those agents to generate the final pulp code.

# The output code will be tested in the following way:
# 1. The generated code will be saved to a .py file.
# 2. The code will be parsed to check for syntax errors.

from jinja2.utils import missing
from pydantic._internal._known_annotated_metadata import constraint_schema_pairings
import os
import warnings
import numpy as np
import pandas as pd
import json
from pathlib import Path
from typing import Any, List

from dotenv import load_dotenv


warnings.filterwarnings("ignore", category=UserWarning, module="langchain_core")

from langchain_ollama import ChatOllama
from langchain.agents import create_agent
from langchain_core.tools import tool
from pydantic import BaseModel, Field, ValidationError
from langchain_core.messages import ToolMessage
import json

from pydantic import BaseModel, Field

# Load environment variables
load_dotenv()

ollama_base_url = os.getenv("OLLAMA_BASE_URL")
ollama_api_key = os.getenv("OLLAMA_API_KEY")

headers = {}
if ollama_api_key and ollama_api_key != "your_api_key_here":
    headers["Authorization"] = f"Bearer {ollama_api_key}"

print(f"Connecting to Ollama at {ollama_base_url}...")

#TOOL CALLS


def _resolve_project_paths() -> tuple[Path, Path]:
    """Return absolute paths for the data and output folders."""
    base_dir = Path(__file__).resolve().parents[1]
    return base_dir / "data", base_dir / "TestOutputs"


def _load_json_file(path: Path) -> Any:
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def _load_text_file(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


@tool
def get_input_schema_payload(
    csv_file_name: str = "optimization_pipeline_test_easy.csv",
    preview_rows: int = 5,
) -> dict[str, Any]:
    """Return the input schema payload produced by the shared CSV schema utility."""
    import importlib.util

    data_dir, _ = _resolve_project_paths()
    module_path = data_dir / "csv_to_input_scheme.py"
    spec = importlib.util.spec_from_file_location("csv_to_input_scheme", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load schema module from {module_path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    if not hasattr(module, "get_input_data"):
        raise AttributeError("csv_to_input_scheme.py does not define get_input_data")

    payload = module.get_input_data(csv_file_name=csv_file_name, preview_rows=preview_rows)

    print(f"Get Input Schema Payload Tool called. Payload: {payload}")
    return payload


@tool
def get_mathematical_model() -> dict[str, Any]:
    """Return the mathematical model payload from generated outputs and reference model."""
    data_dir, outputs_dir = _resolve_project_paths()

    objective_path = outputs_dir / "llm_objective_function.md"
    constraints_path = outputs_dir / "llm_constraints.md"
    documentation_path = outputs_dir / "llm_output.md"

    constraints_raw = _load_text_file(constraints_path)
    constraints_lines = [line.strip() for line in constraints_raw.splitlines() if line.strip()]

    payload: dict[str, Any] = {
        "mathematical_model": {
            "objective_function": _load_text_file(objective_path).strip(),
            "constraint_functions": constraints_lines,
            "readable_documentation": _load_text_file(documentation_path).strip(),
        }
    }

    print(f"Get Mathematical Model Tool called. Payload: {payload}")
    return payload





# --------------------------------------

# PYDANTIC MODELS

class CodeModel(BaseModel):
    """Call this to give the final pulp code output."""
    code: str = Field(description="The generated PuLP code.")
    successful_implementation: bool = Field(description="Whether the code was successfully generated based on the provided information. This should be True if the code is complete and runnable, and False if there are any issues that would prevent the code from running correctly.")

# --------------------------------------
 
# AGENT LOGIC
try:
    llm = ChatOllama(
        base_url=ollama_base_url,
        model="llama3.3:70b-instruct-q3_K_M",
        client_kwargs={"headers": headers} if headers else {},
        reasoning=True,
    )

    tools = [get_input_schema_payload, get_mathematical_model]


    system_message = (
        "You are an expert Operations Research engineer and senior Python developer specialized in PuLP. "
        "Your single task is to convert a given mathematical MILP formulation into a correct, runnable, and well-structured Python PuLP script. "
        "Use only the provided problem information and tools. Do not invent missing business assumptions.\n\n"
        "REQUIRED WORKFLOW:\n"
        "1. First call the context tool calls in the following order:\n"
        "   - get_mathematical_model\n"
        "   - get_input_schema_payload\n"
        "2. Translate sets, indices, parameters, objective, and constraints exactly from the mathematical formulation.\n"
        "3. Build executable PuLP code including: imports, data loading/preparation, index construction, parameter dictionaries, variable declarations, objective, constraints, solve call, and result extraction.\n"
        "4. Ensure the model remains linear and mixed-integer where required (binary/integer/continuous domains and bounds).\n"
        "5. Add concise comments only where logic is non-trivial.\n\n"
        "CORRECTNESS RULES:\n"
        "- Preserve all units and index mappings from the formulation.\n"
        "- Never drop constraints.\n"
        "- Never use nonlinear operations in objective/constraints.\n"
        "- Use deterministic naming for variables and constraints.\n"
        "- Include solver status handling for optimal, infeasible, unbounded, and other statuses.\n"
        "- If data is insufficient to implement a required term, clearly state what is missing instead of guessing.\n\n"
        "OUTPUT REQUIREMENTS:\n"
        "- Produce a complete Python script that can run as a standalone file.\n"
        "- Script must include a main execution path and print key outputs (status, objective value, decision variables).\n"
        "- Ensure syntax is valid Python 3.\n"
        "- Finish by returning the required structured output in the enforced response format.\n\n"
        "STYLE REQUIREMENTS:\n"
        "- Keep code clean and production-like.\n"
        "- Prefer explicit loops/comprehensions that are easy to audit.\n"
        "- Avoid placeholders like TODO, pass, or pseudo-code."
    )

    # Use LangChain's create_agent function as recommended, and enforce structured output
    agent = create_agent(
        model=llm, 
        tools=tools, 
        system_prompt=system_message,
        response_format=CodeModel
    )

    user_input = "Generate the Python PuLP code for the optimization problem. The mathmatical model are provided in the get_mathematical_model tool which you are REQUIRED to call first. The input schema and data information is provided in the get_input_schema_payload tool which you are REQUIRED to call second. Follow the required workflow and correctness rules strictly, and return the complete code in the specified structured format trough calling the CodeModel tool (THIS IS ABSOLUTELY REQUIRED) (Output should be a JSON with fields: code, missing_info, successful_implementation)"   
    print(f"Sending prompt: {user_input}")
    
    messages = [{"role": "user", "content": user_input}]
    max_retries = 3
    
    for attempt in range(max_retries):
        response = agent.invoke({"messages": messages}) # type: ignore
        
        print(f"\n--- Message Trace (Attempt {attempt + 1}) ---")
        for msg in response['messages'][-4:]: # print the last few messages for sanity
            print(f"[{msg.type.upper()}]: {msg.content}")
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                print(f"  Tool Calls: {msg.tool_calls}")
        print("---------------------\n")
        
        # When create_agent succeeds at extracting the structured output, it either terminates
        # with the Tool message containing the stringified result, or the AI message returning the tool call args.
        # Let's inspect the AI message right before the hypothetical tool response or plain content.
        ai_messages = [m for m in response['messages'] if m.type == 'ai']
        final_ai_msg = ai_messages[-1] if ai_messages else None
        
        success = False
        
        # Check if the final AI message correctly made the structured output tool call
        if final_ai_msg and hasattr(final_ai_msg, "tool_calls") and final_ai_msg.tool_calls:
            for tc in final_ai_msg.tool_calls:
                if tc['name'] == 'CodeModel':
                    print("\nSuccess! Parsed Extracted Arguments:")
                    args = tc['args']

                    print("Raw Output: \n" + str(args))
                    code = args.get('code', '')
                    missing_info = args.get('missing_info', '')
                    successful_implementation = bool(args.get('successful_implementation', False))

                    print("\n[Successful Implementation]")
                    print(successful_implementation)

                    print("\n[Missing Info]")
                    print(missing_info if missing_info else "No missing information reported.")

                    print("\n[Generated Code Preview]")
                    if code:
                        print(code[:1000] + ("\n... [truncated]" if len(code) > 1000 else ""))
                    else:
                        print("No code was returned.")

                    _, outputs_dir = _resolve_project_paths()
                    generated_code_path = outputs_dir / "generated_pulp_model.py"

                    try:
                        outputs_dir.mkdir(parents=True, exist_ok=True)
                        with generated_code_path.open("w", encoding="utf-8") as f:
                            f.write(code)
                        print(f"Generated code written to {generated_code_path}")

                        if code:
                            compile(code, str(generated_code_path), "exec")
                            print("Python syntax validation passed.")
                    except SyntaxError as syntax_err:
                        print(f"Generated code has syntax errors: {syntax_err}")
                    except Exception as file_err:
                        print(f"Failed to persist generated code: {file_err}")

                    success = True
                    break
        
        if success:
             break
        else:
             print(f"\nAttempt {attempt + 1} did not return the correct tool call. Retrying...")
             # Let's feed the conversation history back in, appending a strict instruction
             messages = response['messages'] + [
                 {"role": "user", "content": "You failed to output using the required CodeModel format. Please output ONLY by calling the 'CodeModel' tool with all required fields: code, missing_info, successful_implementation."}
             ]
             
    else:
        print("\nFailed to get a valid structured response after maximum retries.")

except Exception as e:
    print(f"\nFailed to connect or generate response. Error: {e}")
