from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
from langchain.agents import create_agent
from langchain_core.tools import tool

from schemas.basemodels import ModellingRecommendation, UseCaseRecommendation

from .shared import (
    build_ollama_model,
    get_data_dir,
    get_test_outputs_dir,
    invoke_structured_agent,
)


def _resolve_csv_path(csv_file_path: str) -> Path:
    csv_path = Path(csv_file_path)
    if csv_path.is_absolute():
        return csv_path

    data_path = get_data_dir() / csv_file_path
    if data_path.exists():
        return data_path

    return csv_path.resolve()


def _load_reference_model() -> dict[str, Any]:
    model_path = get_data_dir() / "ReferenceMathematicalModel.json"
    if not model_path.exists():
        return {}

    return json.loads(model_path.read_text(encoding="utf-8"))


def _persist_outputs(recommendation: ModellingRecommendation) -> None:
    outputs_dir = get_test_outputs_dir()
    outputs_dir.mkdir(parents=True, exist_ok=True)

    (outputs_dir / "llm_objective_function.md").write_text(
        recommendation.objective_function.strip(),
        encoding="utf-8",
    )
    (outputs_dir / "llm_constraints.md").write_text(
        "\n".join(constraint.strip() for constraint in recommendation.constraint_functions),
        encoding="utf-8",
    )
    (outputs_dir / "llm_output.md").write_text(
        recommendation.readable_documentation.strip(),
        encoding="utf-8",
    )


def run_modeling_agent(
    csv_file_path: str,
    use_case: UseCaseRecommendation | None,
    preview_rows: int = 5,
) -> ModellingRecommendation:
    """Generate a MILP recommendation and persist markdown artifacts."""
    resolved_csv_path = _resolve_csv_path(csv_file_path)
    if not resolved_csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {resolved_csv_path}")

    @tool
    def get_column_names() -> dict[str, Any]:
        """Return available CSV columns and a compact preview."""
        df_preview = pd.read_csv(resolved_csv_path, nrows=preview_rows)
        columns = [str(column) for column in df_preview.columns.tolist()]
        return {
            "csv_file_path": str(resolved_csv_path),
            "columns": columns,
            "preview_rows": df_preview.to_dict(orient="records"),
        }

    @tool
    def get_reference_model() -> dict[str, Any]:
        """Return a reference model JSON used as notation style hint."""
        return _load_reference_model()

    @tool
    def get_use_case_recommendation() -> dict[str, Any]:
        """Return selected use-case metadata from the previous graph node."""
        if use_case is None:
            return {
                "use_case_name": "Production Planning",
                "business_goal": "Maximize production profit with available resources.",
                "objective_direction": "max",
                "objective_variable": "total profit",
                "decision_variables": ["production_quantity_per_product"],
                "required_columns": [],
                "constraints_to_consider": [],
                "assumptions": [
                    "Use-case agent result missing; fallback use case selected."
                ],
                "rationale": "Fallback use case generated by modeling agent.",
            }

        return use_case.model_dump()

    llm = build_ollama_model()
    agent = create_agent(
        model=llm,
        tools=[get_column_names, get_reference_model, get_use_case_recommendation],
        system_prompt=(
            "You are an operations research expert. Build a mathematically correct MILP model from the available CSV data and use-case recommendation. "
            "Always call tools to inspect real inputs before writing the model. "
            "Output must be a ModellingRecommendation structured tool call only.\n\n"
            "Required tool sequence:\n"
            "1. Call get_use_case_recommendation\n"
            "2. Call get_column_names\n"
            "3. Call get_reference_model\n\n"
            "Required fields: col_names_used, parameters, variables, minimizing_problem, objective_function, "
            "constraint_functions, explanation_of_ILP, readable_documentation."
        ),
        response_format=ModellingRecommendation,
    )

    args = invoke_structured_agent(
        agent=agent,
        user_input=(
            "Create a MILP formulation for the selected use case using only information from tool outputs. "
            "Provide pseudo-LaTeX expressions and concise explanation_of_ILP entries."
        ),
        response_tool_name="ModellingRecommendation",
        retry_message=(
            "Your previous answer did not use the required ModellingRecommendation tool call. "
            "Return only a valid ModellingRecommendation with all required fields."
        ),
        response_model=ModellingRecommendation,
    )

    recommendation = ModellingRecommendation.model_validate(args)
    _persist_outputs(recommendation)
    return recommendation


if __name__ == "__main__":
    result = run_modeling_agent(
        csv_file_path="optimization_pipeline_test_easy.csv",
        use_case=None,
        preview_rows=5,
    )
    print(result.model_dump_json(indent=2))
